### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim.github.io#2]
I'm going to rename this repo to something simpler if no one objects to it. 

/mars-sim.github.io is a little too long. Sorry Lars, I know you ask me once what I prefer. I thought you ask me the url for our website.

Do you guys like /html or /webpage or something else ?

**Comment by larsnaesbye** [comment]
Check if this will break the mapping - it was the standard setup for Github Pages.

**Comment by mokun** [comment]
Yes it breaks the mapping. 


After I changed it to /website, I went to https://github.com/mars-sim/mars-sim.github.io/settings to take a look at "GitHub Pages" heading to see if the site retains the link of https://mars-sim.github.io/. 

Unfortunately, it didn't. So I had to revert the change back to what it used to be :(

**Comment by larsnaesbye** [comment]
I don't remember if there still is an alternative way with GH Pages. In my abandoned project I have as repo https://github.com/larsnaesbye/tempus and the webpage at http://larsnaesbye.github.io/tempus/ because the pages are in a branch called 'gh-pages'.

**Comment by larsnaesbye** [comment]
For the time being there's no easy fix, and it's not that important.
