### ISSUE TITLE
Replace with a newer version of the html5up template

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim.github.io#3]
@bevans2000 

Currently, our project website uses a custom template based on html5up's prologue edition.

However, it's out-dated and the old jsquery it uses would throw up security violations.

We can find the latest version is at : 
https://html5up.net/prologue

We should at least update it to the latest version of prologue or find a better template for our use case.

e.g. Do we want to maintain a blog to describe what we do ?

**Comment by bevans2000** [comment]
Good old jquery....
I'll sort this. But where is the banner.jpg?.

**Comment by mokun** [comment]
> But where is the banner.jpg?

We don't have one.

Do you need it ?

**Comment by mokun** [comment]
May be we can designate the following pic as the banner pic ?

![image](https://github.com/mars-sim/mars-sim.github.io/assets/1168584/9045f2e3-4f42-4b25-addb-da7822900427)

**Comment by bevans2000** [comment]
Updated
