### ISSUE TITLE
Use static site generator

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim.github.io#5]
@bevans2000 

As a follow-up to the issue at https://github.com/mars-sim/mars-sim/issues/834#issuecomment-2466950350,

May be we can consider using https://github.com/jackyzha0/quartz ?

**Comment by bevans2000** [comment]
Interesting, I like https://jekyllrb.com/ because it is already integrated into GitHub Pages and does not need any special tooling on the client. It also supports markdown and html content. I plan to have a play soon.

**Comment by bevans2000** [comment]
@mokun I've played with Jekyll today and splitting up the existing web page content.
I've also added one of the generated vehicle spec pages to see how it behaves. It would be possible to generated all the same page set for the website.
Structure is great and we could move lots of the main readme file into this as dedicated pages.
However the style needs work but it's easy to switch another theme if we find one.
https://bevans2000.github.io/

**Comment by mokun** [comment]
> @mokun I've played with Jekyll today .

Yes Jekyll is quite good for our use already

> Structure is great and we could move lots of the main readme file into this as dedicated pages.

Ok. So what do we eventually want to show in readme.md ?

> However the style needs work but it's easy to switch another theme if we find one.

Right.

I wonder if jekyll supports responsive web page or not.

> https://bevans2000.github.io/

Is it easy to configure git action?

**Comment by bevans2000** [comment]
Yes, this layout is responsive. And it's using the standard GitHub in action.

The readme has a lot of content about the thinking and approach to the simulation and that would be better on a web site. The readme should be focused on developers and a high level overview.

**Comment by bevans2000** [comment]
@mokun  I have done more reworking of prototype of the new web site; https://bevans2000.github.io/
I have now improved how the configuration entities are generated including the addition of ConstructionStage & ResupplyManifest.

**Comment by mokun** [comment]
> eworking of prototype of the new web site; https://bevans2000.github.io/

That's awesome.

I can see you have added a dozen of those "Simulation Entities" so far.  They look good.

We'll update all screenshots in near future.

**Comment by bevans2000** [comment]
@mokun have you noticed that the marssim.space web site seems slow? Looks like when using GitHub pages it sometimes takes a while to return the page. So if it's not well used it takes a while to load.
I wonder if we should consider hosting it elsewhere like in AWS S3?

**Comment by mokun** [comment]
>  marssim.space web site seems slow?

No it's blazing fast from where I am. Is the problem geographically related ?

**Comment by bevans2000** [comment]
That's good then. No need to change it
